version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 &&
             python app/commands/managements/create_techs.py"
    volumes:
      - .:/app
    ports:
      - 80:8000